name: Cron job Merge Staging into Main

on:
  workflow_dispatch:
    inputs:
      run_job:
        description: 'Execute manually'
        required: true
        default: 'yes'
  schedule:
    - cron: '0 17 1,15 * *'  # execute monthly on day 1 and 15 at 17:00 UTC

permissions: write-all

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup node
        uses: actions/setup-node@v4.0.0
        with:
          node-version: '^18.0.0'
          cache: 'npm'

      - name: Install
        run: npm ci

      - uses: actions/cache@v3.3.2
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}
  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup node
        uses: actions/setup-node@v4.0.0
        with:
          node-version: '^18.0.0'
          cache: 'npm'

      - uses: actions/cache@v3.3.2
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup node
        uses: actions/setup-node@v4.0.0
        with:
          node-version: '^18.0.0'
          cache: 'npm'

      - uses: actions/cache@v3.3.2
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}
      
      - name: Build
        run: npm run build --if-present
        env:
          NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
          NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.SANITY_DATASET }}

  merge:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

    - name: Configure user
      run: |
        git remote set-url origin "https://${{ secrets.CV_DEVS_PAT }}@github.com/clearviction-devs/clearviction-wa.git"

    - name: Get and Update staging branch
      run: |
        git fetch origin staging
        git checkout staging
        git pull origin staging
        git checkout main

    - name: Merge to Main and Push
      run: |
        git merge --ff-only staging
        git push origin main
  
  handle-fail:
    runs-on: ubuntu-latest
    needs: [install, lint, build, merge]
    if: failure()
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Check Workflow Status
      run: gh issue create --title "Failed Merge" --body "Workflow that merge staging to main failed. Please check logs."
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

